### ISSUE TITLE
Figure out what to do with rbi.yaml

### ISSUE THREAD

**Issue by searls** [standardrb/standard-sorbet#2]
rubocop-sorbet [ships with this config for rbi files](https://github.com/Shopify/rubocop-sorbet/blob/main/config/rbi.yml) and I'm unsure what to do about it. 

We can't just merge it into the config for RBI files b/c it reconfigures a bunch of base rubocop rules (which is disallowed by Standard).

The one idea I have is for a plugin setting like this:

```yaml
plugins:
  - standard-sorbet:
      ignore_unnecessary_rules_for_rbi_files: true
```

And then given that configuration, add in a nested ignore somehow (off the top of my head I'm not sure this would work), similar to how you can ignore rules for entire globs in standard.yml

```yaml
ignore:
  - '*.rbi':
    - Layout/AlignHash
    # … etc etc
```

Unsure what else might make sense or be workable
