### ISSUE TITLE
Remove metadata owned by ruboocop-sorbet from our base.yml

### ISSUE THREAD

**Issue by searls** [standardrb/standard-sorbet#3]
We don't want to own a duplication of all the metadata copied from the default.yml of rubocop-sorbet in our [base.yml](/config/base.yml), because it's too much work to keep them in sync

For example:

```yaml
Sorbet/CallbackConditionalsBinding:
  Description: 'Ensures callback conditionals are bound to the right type.'
  Enabled: false
  Safe: false
  VersionAdded: 0.7.0
```

Should be in this repo just as:

```yaml
Sorbet/CallbackConditionalsBinding:
  Enabled: false
```

However, just doing this will (may?) strip that metadata at runtime since we're not invoking `require "rubocop-sorbet"` to work around the inject monkey patch. We may need to merge this in dynamically in the plugin or using a yaml config. Need to test this.

The same issue applies to https://github.com/standardrb/standard-rails come to think of it
